seed: 1101
model:
    learning_rate: 0.000045

data_module:
    root_dir: /root/paddlejob/workspace/env_run/SuperBench/climate
    variables:
        - "2m_temperature"
    batch_size: 24
    num_workers: 1
    upscale_factor: 4
    crop_size: 720
    method: bicubic
    noise_ratio: 0.0

trainer:
    max_epochs: 50
    gpus: -1
