seed: 101
model:
    learning_rate: 0.000001
    l_encoder_checkpoint_path: vq_vae_low.ckpt
    h_decoder_checkpoint_path: vq_vae_high.ckpt
    f_loss_checkpoint_path: forward_net.ckpt
    b_loss_checkpoint_path: backward_net.ckpt

data_module:
    root_dir: /root/paddlejob/workspace/env_run/SuperBench/climate
    variables:
        - "2m_temperature"
    batch_size: 4
    num_workers: 1
    upscale_factor: 4
    crop_size: 720
    method: bicubic
    noise_ratio: 0.0

scheduler:
    warmup_epochs: 10

trainer:
    max_epochs: 50
    gpus: -1
