seed: 11
model:
    net_type: b
    l_encoder_checkpoint_path: vq_vae_low.ckpt
    h_encoder_checkpoint_path: vq_vae_high.ckpt
    learning_rate: 0.000045
    warmup_epochs: 5
    max_epochs: 100

data_module:
    root_dir: /root/paddlejob/workspace/env_run/SuperBench/climate
    variables:
        - "2m_temperature"
    out_variables:
        - "2m_temperature"
    batch_size: 4
    num_workers: 1
    upscale_factor: 4
    crop_size: 720
    method: bicubic
    noise_ratio: 0.0
    seq_len: 2

scheduler:
    warmup_epochs: 10

trainer:
    max_epochs: 50
    gpus: -1
